#!/usr/bin/env python3
"""Generate the Chitonga audio recording list from the content pack.

Every audioKey in the content pack is exactly one clip to record. Re-running
after content edits reports which clips are new and which are now orphaned.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACK = ROOT / "TongaKids/Resources/Raw/content/chitonga-content.json"
AUDIO_DIR = ROOT / "TongaKids/Resources/Raw/audio"
OUT = ROOT / "docs/audio-recording-list.md"

pack = json.loads(PACK.read_text(encoding="utf-8"))

clips = []
for level in pack["levels"]:
    for lesson in level["lessons"]:
        for item in lesson["items"]:
            key = item.get("audioKey", "").strip()
            if key:
                clips.append((key, item["grapheme"], level["title"], lesson["title"]))

existing = {p.stem for p in AUDIO_DIR.glob("*.m4a")} if AUDIO_DIR.is_dir() else set()
needed = {c[0] for c in clips}

lines = [
    "# Chitonga audio recording list",
    "",
    "Generated by `tools/generate-audio-manifest.py`. Do not edit by hand.",
    "",
    "**Format:** mono, 44.1 kHz, `.m4a`. Save into `TongaKids/Resources/Raw/audio/`",
    "using exactly the filename in the first column.",
    "",
    f"**Status:** {len(needed - existing)} to record, {len(needed & existing)} done.",
    "",
    "| Filename | Say this | Level | Lesson | Recorded |",
    "|---|---|---|---|---|",
]
for key, grapheme, level_title, lesson_title in clips:
    mark = "yes" if key in existing else " "
    lines.append(f"| `{key}.m4a` | **{grapheme}** | {level_title} | {lesson_title} | {mark} |")

orphans = sorted(existing - needed)
if orphans:
    lines += ["", "## Orphaned clips", "",
              "These files exist but no content references them:", ""]
    lines += [f"- `{o}.m4a`" for o in orphans]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {OUT.relative_to(ROOT)}: {len(clips)} clips, "
      f"{len(needed - existing)} still to record.")
